// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {transformstruct} from '../models';

export function TransformStruct(arg1:transformstruct.Request):Promise<any|Error>;
