// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function TransformStruct(arg1) {
  return window['go']['transformstruct']['TransformStruct']['TransformStruct'](arg1);
}
