// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {getjson} from '../models';

export function Get(arg1:getjson.Input):Promise<string|Error>;
