// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {setjson} from '../models';

export function Set(arg1:setjson.Input):Promise<string|Error>;
