// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dnslookup} from '../models';

export function Lookup(arg1:dnslookup.Input):Promise<dnslookup.Output|Error>;
