// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Lookup(arg1) {
  return window['go']['dnslookup']['DnsLookup']['Lookup'](arg1);
}
