// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {packageinsights} from '../models';

export function GetPackageInsight(arg1:packageinsights.Request):Promise<packageinsights.Response|Error>;
