// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function JsonToGo(arg1) {
  return window['go']['app']['App']['JsonToGo'](arg1);
}

export function ParseUrl(arg1) {
  return window['go']['app']['App']['ParseUrl'](arg1);
}
