// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';

export function JsonToGo(arg1:app.JsonToGoInput):Promise<any|Error>;

export function ParseUrl(arg1:string):Promise<app.ParseResult|Error>;
