// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';

export function GetPackageInsight(arg1:app.GetPackageInsightsRequest):Promise<app.GetPackageInsightsResponse|Error>;
