// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';

export function TransformStruct(arg1:app.TransformStructRequest):Promise<any|Error>;
