// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {parseurl} from '../models';

export function ParseUrl(arg1:string):Promise<parseurl.Response|Error>;
