// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ParseUrl(arg1) {
  return window['go']['parseurl']['ParseUrl']['ParseUrl'](arg1);
}
